"""
Django Settings for Main Frame Project

Core configuration for the Django backend application. Configures:
- Database connection (PostgreSQL via environment variables)
- Installed apps (Django REST Framework, CORS headers, Pogoda API)
- CORS policy (allows frontend access from localhost:5000)
- Rate limiting (10 requests/minute per anonymous IP for anti-scraping)
- Security middleware and authentication

Generated by 'django-admin startproject' using Django 5.1.3.
For more information on this file, see:
    https://docs.djangoproject.com/en/5.1/topics/settings/
"""

from pathlib import Path
import os

# Base directory of the Django project (two levels up from this file)
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Security Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5wmlx--977^w7ef*1c)vhqtajrhkmm^1)b@+3-y8!t7v!1n-(q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts for development; restrict in production
ALLOWED_HOSTS = ['*']


# --- Application Definition ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',       # Django REST Framework for API endpoints
    'corsheaders',          # CORS headers for cross-origin frontend requests
    'pogoda_api',           # Pogoda portfolio API app
    'beauty_api',           # Beauty marketplace API app
    'bff_api',              # Backend-for-Frontend middleware (SDUI orchestrator)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'beauty_api.middleware.BeautyAuthMiddleware',  # Device-bound cookie auth for Beauty routes
]

ROOT_URLCONF = 'main_frame_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_frame_project.wsgi.application'


# --- Database Configuration ---
# PostgreSQL connection using environment variables set by Replit's
# built-in database provisioning (PGDATABASE, PGUSER, PGPASSWORD, etc.)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PGDATABASE'),
        'USER': os.environ.get('PGUSER'),
        'PASSWORD': os.environ.get('PGPASSWORD'),
        'HOST': os.environ.get('PGHOST'),
        'PORT': os.environ.get('PGPORT'),
    }
}


# --- Password Hashing ---
# BCryptSHA256PasswordHasher is the primary hasher.
# SHA-256 pre-hashing removes bcrypt's 72-byte password length limit.
# Django's make_password() and check_password() use this automatically,
# so no changes are needed in models or views.
# The fallback hashers allow existing PBKDF2 hashes to be verified
# (e.g. any rows that existed before this change) and re-hashed to
# bcrypt on next successful login.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- Static Files ---
STATIC_URL = 'static/'

# --- Default Primary Key ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CORS Configuration ---
# Explicitly allowed origins for production-like environments
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5000",
    "http://127.0.0.1:5000",
]

# Allow all origins in development mode for easier testing
CORS_ALLOW_ALL_ORIGINS = os.environ.get('DEBUG', 'True') == 'True'

# Required so the browser sends cookies and the X-Device-ID header cross-origin
CORS_ALLOW_CREDENTIALS = True

# Expose the custom device-ID header to CORS preflight checks
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-device-id',  # Custom header used to bind requests to a specific device
]


# --- Beauty Auth Cookie Configuration ---
BEAUTY_SESSION_COOKIE_AGE = 86400  # 24 hours in seconds

# Window (minutes) after a booking is created during which the customer
# can cancel "immediately" — refund + booking is hidden from history.
# After this window the regular `cancel` action sets the booking to
# `cancelled_by_customer` with no automatic refund.
BEAUTY_GRACE_PERIOD_MINUTES = 5

# When True, refresh the auth cookie if it's within this many seconds of
# expiry. Used by the /api/beauty/session/refresh/ endpoint.
BEAUTY_SESSION_REFRESH_WINDOW_SECONDS = 3600  # 1 hour


# --- REST Framework Configuration ---
# Rate limiting: 10 requests/minute per anonymous IP address
# Protects against scraping and excessive API usage
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'main_frame_project.throttling.LocalhostExemptAnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/minute',
    }
}
