"""Locators for the RN booking detail screen (`(customer)/bookings/[id]`)."""

booking_service_name = "css=[data-testid='booking-service-name']"
booking_status = "css=[data-testid='booking-status']"
booking_summary_card = "css=[data-testid='booking-summary-card']"
booking_provider_card = "css=[data-testid='booking-provider-card']"
booking_grace_strip = "css=[data-testid='booking-grace-strip']"
booking_reschedule = "css=[data-testid='booking-reschedule']"
booking_cancel_grace = "css=[data-testid='booking-cancel-grace']"
booking_cancel = "css=[data-testid='booking-cancel']"
booking_open_chat = "css=[data-testid='booking-open-chat']"
booking_view_provider = "css=[data-testid='booking-view-provider']"
booking_back = "css=[data-testid='booking-back']"
booking_detail_error = "css=[data-testid='booking-detail-error']"
