Feature: Kevin Experience Page Validation

  Scenario: Verify all experience details are displayed
    Given I navigate to kevin home page
    When I click on the Experience link
    Then it should display the Experience header "Experience"
    And it should display the category "Languages"
    And it should display the skill "HTML5"
    And it should display the skill "JavaScript"
    And it should display the skill "Python"
    And it should display the skill "CSS3"
    And it should display the skill "SQL"
    And it should display the skill "Java"
    And it should display the category "Frameworks"
    And it should display the skill "Salesforce Admin"
    And it should display the skill "YAML"
    And it should display the skill "Angular"
    And it should display the skill "React"
    And it should display the skill "Spring Framework"
    And it should display the skill "Salesforce Developer"
    And it should display the category "Database and Tools"
    And it should display the skill "MySQL"
    And it should display the skill "Android Studio"
    And it should display the skill "Confluence"
    And it should display the skill "MongoDB"
    And it should display the skill "Azure"
    And it should display the skill "TensorFlow"
    And it should display the category "Testing"
    And it should display the skill "TestNG"
    And it should display the skill "JUnit"
    And it should display the skill "Playwright"
    And it should display the skill "Appium Testing"
    And it should display the skill "Selenium"
    And it should display the skill "ADA Testing"
    And it should display the category "Dev-Ops"
    And it should display the skill "GitHub Actions"
    And it should display the skill "Kubernetes"
    And it should display the skill "Terraform"
    And it should display the skill "Docker"
    And it should display the skill "Unix"
    And it should display the skill "Jira"
    And it should display the category "General"
    And it should display the skill "Microsoft Office"
    And it should display the skill "VBA for Excel"
    And it should display the skill "Browser Stack"
    And it should display the skill "Hexawise"
    And it should display the skill "Jenkins"
    And it should display the skill "Salesforce Developer"