"""Locators for the business home (calendar + gauges) screen."""

home_root = "css=div.beauty-app.prov-shell"
biz_title = "css=div.beauty-app.prov-shell div.biz-name"
calendar_grid = "css=div.beauty-app.prov-shell div.cal-grid"
today_cell = "css=div.beauty-app.prov-shell button.cal-cell.is-today"
day_cell = "css=div.beauty-app.prov-shell button.cal-cell[data-date='{date}']"
day_bookings = "css=div.beauty-app.prov-shell div.day-bookings"
gauge_earnings_value = "css=div.beauty-app.prov-shell div.arc-value strong"
gauge_volume_value = "css=div.beauty-app.prov-shell div.vol-total strong"
services_button = "css=div.beauty-app.prov-shell button.tab >> text=Services"
profile_button = "css=div.beauty-app.prov-shell button.tab >> text=Profile"
