business_login_page_root = "css=div.business-login-page"
business_badge = "css=div.business-login-page span.business-badge"
business_login_title = "css=div.business-login-page h1.login-title"
business_login_subtitle = "css=div.business-login-page p.login-subtitle"
email_input = "css=div.business-login-page input#email"
password_input = "css=div.business-login-page input#password"
password_toggle_button = "css=div.business-login-page button.password-toggle"
submit_button = "css=div.business-login-page button.btn-business"
server_error = "css=div.business-login-page div.server-error"
customer_signin_link_button = "css=div.business-login-page button.link-signup"
brand_name_button = "css=div.business-login-page button.brand-name-btn"
