"""Locators for the business home (calendar + gauges) screen."""

home_root = "css=div.pw-shell"
biz_title = "css=div.pw-shell div.biz-name"
calendar_grid = "css=div.pw-shell div.cal-grid"
today_cell = "css=div.pw-shell button.cal-cell.is-today"
day_cell = "css=div.pw-shell button.cal-cell[data-date='{date}']"
day_bookings = "css=div.pw-shell div.day-bookings"
gauge_earnings_value = "css=div.pw-shell div.arc-value strong"
gauge_volume_value = "css=div.pw-shell div.vol-total strong"
services_button = "css=div.pw-shell a.pw-nav-item >> text=Services"
profile_button = "css=div.pw-shell a.pw-nav-item >> text=Profile"
