login_page_root = "css=div.login-page:not(.business-login-page)"
login_title = "css=.login-page:not(.business-login-page) h1.login-title"
login_subtitle = "css=.login-page:not(.business-login-page) p.login-subtitle"
email_input = "css=.login-page:not(.business-login-page) input#email"
password_input = "css=.login-page:not(.business-login-page) input#password"
password_toggle_button = "css=.login-page:not(.business-login-page) button.password-toggle"
submit_button = "css=.login-page:not(.business-login-page) button.btn-login[type='submit']"
server_error = "css=.login-page:not(.business-login-page) div.server-error"
signup_link_button = "css=.login-page:not(.business-login-page) button.link-signup"
business_login_link_button = "css=.login-page:not(.business-login-page) button.link-business"
brand_name_button = "css=.login-page:not(.business-login-page) button.brand-name-btn"
