signup_page_root = "css=div.signup-page"
signup_title = "css=div.signup-page h1.signup-title"
email_input = "css=div.signup-page input#email"
password_input = "css=div.signup-page input#password"
password_toggle_button = "css=div.signup-page button.password-toggle"
submit_button = "css=div.signup-page button.btn-continue"
server_error = "css=div.signup-page div.server-error"
signin_link_button = "css=div.signup-footer button.link-btn"
brand_name_button = "css=div.signup-page button.brand-name-btn"
