name: Docker Compose

on:
  push:
  workflow_dispatch:
    inputs:
      compose-file:
        description: "Compose file path"
        default: "docker-compose.yml"
        type: string

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run docker-compose up
        run: |
          docker compose up -d
          sleep 30

      - name: Call automation testing
        uses: ./.github/workflows/automationTestingWithPlaywright.yml
        with:
          python-version: "3.10"

      - name: Run docker-compose down
        run: docker compose down
