name: Docker Compose Teardown

on:
  workflow_call:

jobs:
  teardown:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Stop Docker Compose
        run: docker compose down
