name: Docker Compose and Playwright Tests

on:
  push:

env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
jobs:
  build:
    runs-on: ubuntu-latest
    
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose watch
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV

  end-to-end:
      needs: build
      uses: PogodaSoftware/Automation_Testing_with_Playwright/.github/workflows/docker-compose-playwright.yml@main
     
  stop-test:
    needs: end-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
