name: Docker Compose and Playwright Tests

on:
  push:
 

jobs:
  build:
    runs-on: ubuntu-latest

  end-to-end:
      needs: build
      uses: PogodaSoftware/Automation_Testing_with_Playwright/.github/workflows/docker-compose-playwright.yml@main
