name: Docker Compose and Playwright Tests

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the application"

  dockerise:
    needs: build
    uses: ./.github/workflows/dockerise.yml
    secrets:
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}

  

  teardown:
      needs:
        - dockerise
      runs-on: ubuntu-latest
      steps:
        - name: Stop Docker Compose
          if: always()
          run: docker compose down