name: Dockerisation of the Application

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright/run_tests.py"
        type: string
    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env

      - name: Start Docker Compose
        run: |
          docker-compose up -d
          sleep 5

      - name: Checkout Playwright tests repository
        uses: actions/checkout@v4
        with:
          repository: PogodaSoftware/Au-tomation_Testing_with_Playwright
          path: Automation

      - name: Run Playwright tests
        uses: PogodaSoftware/Automation_Testing_with_Playwright/.github/workflows/docker-compose-playwright.yml@main
        with:
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down