name: Docker Compose and Playwright Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright-tests/test_homePage.py"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run Django setup
        run: |
          python /main_frame/Backend/controller/manage.py migrate
          python /main_frame/Backend/controller/manage.py collectstatic --noinput

      - name: Run Playwright Tests
        run: |
          mkdir -p test-results
          python ${{ inputs.test-script }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 1

      - name: Stop Docker Compose
        if: always()
        run: docker compose down