name: Docker Compose and Playwright Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright-tests/test_homePage.py"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Playwright Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python Playwright-tests/run_tests.py

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
