name: Docker Compose and Playwright Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright-tests/test_homePage.py"
        type: string
      requirements-file:
        description: "Path to the requirements file"
        default: "Backend/controller/requirements.txt"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Start Docker Compose
      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 30 # Consider replacing with health checks

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-file }}

      # Step 5: Run Playwright Tests
      - name: Run Playwright Tests
        run: |
          mkdir -p test-results
          python ${{ inputs.test-script }}

      # Step 6: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 1

      # Step 7: Stop Docker Compose
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
