name: Dockerisation of the Application

on:
  workflow_call:
    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
      PATTOKEN: ${{ secrets.PAT_TEST }}
    timeout-minutes: 30
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        shell: bash
        run: |
          docker compose up -d
          sleep 5
  
        
      - name: Trigger External Playwright Tests
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ORGPAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PogodaSoftware/Automation/actions/workflows/pythonplaywright.yml/dispatches \
          -d '{"ref":"main"}'
            
      - name: Stop Docker Compose
        shell: bash
        if: always()
        run: docker compose down  
        
