name: Docker Compose and Playwright Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright/run_tests.py"
        type: string
    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true
env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Playwright Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python ${{ inputs.test-script }}

      - name: Stop Docker Compose
        if: always() 
        run: docker compose down







# name: Dockerisation of the Application

# on:
#   workflow_call:
#     inputs:
#       python-version:
#         description: "Python version to use"
#         default: "3.11"
#         type: string
#       test-script:
#         description: "Path to the Playwright test script in the external repository"
#         default: "Playwright/run_tests.py"
#         type: string
#     secrets:
#       BACKEND_PORT:
#         required: true
#       FRONTEND_PORT:
#         required: true

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     env: 
#       BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
#       FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
#       PATTOKEN: ${{ secrets.PAT_TEST }}
#     timeout-minutes: 30
#     services:
#       docker:
#         image: docker:20.10.9
#         options: --privileged

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Start Docker Compose
#         run: |
#           docker compose up -d
#           sleep 5
        
#       - name: Trigger External Playwright Tests
#         run: |
#             echo PAT is $PATTOKEN
#             curl -L \
#              -X POST \
#               -H "Accept: application/vnd.github+json" \
#               -H "Authorization: Bearer ${PATTOKEN}" \
#               -H "X-GitHub-Api-Version: 2022-11-28" \
#               https://api.github.com/repos/PogodaSoftware/Automation_Testing_with_Playwright/actions/workflows/python-test-with-playwright.yml/dispatches \
#               -d '{
#                 "ref": "main",
#                 "inputs": {
#                   "BACKEND_PORT": "'"${{ secrets.BACKEND_PORT }}"'",
#                   "FRONTEND_PORT": "'"${{ secrets.FRONTEND_PORT }}"'",
#                   "python-version": "'"${{ inputs.python-version }}"'",
#                   "test-script": "'"${{ inputs.test-script }}"'"
#                 }
#               }'

#       - name: Debug Secrets
#         run: echo "PAT is set"
#         env:
#           PAT: ${{ secrets.PAT }}
            
        
#       - name: Stop Docker Compose
#         if: always()
#         run: docker compose down
