name: Dockerisation of the Application

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script in the external repository"
        default: "Playwright/run_tests.py"
        type: string
    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    timeout-minutes: 30
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

          - name: Trigger External Playwright Tests
          uses: actions/github-script@v6
          with:
            script: |
              const inputs = {
                'python-version': '3.11',
                'test-script': 'Playwright/run_tests.py',
              };
              await github.rest.actions.createWorkflowDispatch({
                owner: 'PogodaSoftware',
                repo: 'Automation_Testing_with_Playwright',
                workflow_id: 'python-test-with-playwright.yml',
                ref: 'main',
                inputs,
              });
            
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
