name: Dockerisation of the Application

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        type: string
      test-script:
        description: "Path to the Playwright test script"
        default: "Playwright/run_tests.py"
        type: string
    secrets:
      BACKEND_PORT:
        required: true
      FRONTEND_PORT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    timeout-minutes: 15
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Playwright tests
        run:  PogodaSoftware/Automation_Testing_with_Playwright/.github/workflows/docker-compose-playwright.yml@main
      

      - name: Stop Docker Compose
        if: always()
        run: docker compose down