name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Backend/controller/requirements.txt"

      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps

      - name: Debug Environment Variables
        run: echo "FRONTEND_PORT=$FRONTEND_PORT"

      - name: Run Playwright Tests
        run: python Playwright/run_tests.py
