name: Python Unit Tests

on:
  [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/controller/requirements.txt

      - name: Add execute permissions for test_runner.py
        run: chmod +x Backend/controller/test/test_runner.py
        
      - name: Run your tests
        run: python Backend/controller/test/test_runner.py

      - name: Run docker-compose down
        run: docker compose down
