name: Run Tests with Reusable Workflow

on: [pull_request]

jobs:
  run-tests:
    uses: ./.github/workflows/docker-compose-playwright.yml
    with:
      python-version: "3.11"
      test-script: "Playwright-tests/run_tests.py"
