name: Run Tests with Reusable Workflow

on:
  [ push ]
   

jobs:
  run-tests:
    uses: ./.github/workflows/docker-compose-playwright.yml
    with:
      python-version: "3.10"
      test-script: "Playwright-tests/test_homePage.py"
