name: Docker Compose Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose up
        run: |
          docker compose up -d
          sleep 30
